max-players: 2
min-players: 1
matrix-size: 4
build-area-size: 65
plot-floor-material: WHITE_CONCRETE
plot-wall-material: WHITE_CONCRETE
plot-wall-height: 50
plot-ring-material: LIGHT_GRAY_CONCRETE
max-build-height: 40
countdown-seconds: 5
theme-vote-seconds: 5
build-seconds: 180
evaluation-seconds-per-plot: 10

# Sound configuration
sounds:
  enabled: true
  ui_click:
    sound: ENTITY_EXPERIENCE_ORB_PICKUP
    volume: 0.6
    pitch: 1.2
  phase_complete:
    sound: ENTITY_PLAYER_LEVELUP
    volume: 0.9
    pitch: 1.0
  countdown_tick:
    sound: ENTITY_EXPERIENCE_ORB_PICKUP
    volume: 0.6
    pitch_start: 0.9
    pitch_step: 0.05
  build_tick:
    alternate: true
    sound_a: BLOCK_NOTE_BLOCK_BASEDRUM
    pitch_a: 0.8
    sound_b: BLOCK_NOTE_BLOCK_SNARE
    pitch_b: 1.0

worlds:
  lobby: world
  game: world

lobby-spawn:
  world: world
  x: 0.5
  y: 69.0
  z: 0.5
  yaw: 0.0
  pitch: 0.0

lobby-platform:
  size: 7
  material: QUARTZ_BLOCK

arena-origin:
  world: world
  x: 100.0
  y: 64.0
  z: 100.0
plot-gap: 5

void-world:
  biome: THE_VOID
  # Optionally set default spawn for newly created void worlds (only informational; creation handled by server)
  spawn:
    x: 0.5
    y: 64.0
    z: 0.5

